//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AeccApp.Internationalization.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationResourcesAecc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResourcesAecc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AeccApp.Internationalization.Properties.LocalizationResourcesAecc", typeof(LocalizationResourcesAecc).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noticias.
        /// </summary>
        public static string AllNewsViewTitle {
            get {
                return ResourceManager.GetString("AllNewsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domicilio.
        /// </summary>
        public static string AllYourRequestsHome {
            get {
                return ResourceManager.GetString("AllYourRequestsHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital.
        /// </summary>
        public static string AllYourRequestsHospital {
            get {
                return ResourceManager.GetString("AllYourRequestsHospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todavía no has hecho ninguna petición desde domicilio..
        /// </summary>
        public static string AllYourRequestsListNoHomeRequests {
            get {
                return ResourceManager.GetString("AllYourRequestsListNoHomeRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todavía no has hecho ninguna petición desde hospital..
        /// </summary>
        public static string AllYourRequestsListNoHospitalRequests {
            get {
                return ResourceManager.GetString("AllYourRequestsListNoHospitalRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Ups!.
        /// </summary>
        public static string AllYourRequestsListOops {
            get {
                return ResourceManager.GetString("AllYourRequestsListOops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danos un momento, estamos conectando con el voluntario..
        /// </summary>
        public static string ChatConnectingPopupText {
            get {
                return ResourceManager.GetString("ChatConnectingPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abre un nuevo chat, elige y habla con el voluntario que más se adapte a tus preferencias y necesidades..
        /// </summary>
        public static string ChatListViewText {
            get {
                return ResourceManager.GetString("ChatListViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string ChatListViewTitle {
            get {
                return ResourceManager.GetString("ChatListViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string ChatRequestAccept {
            get {
                return ResourceManager.GetString("ChatRequestAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petición de asistencia..
        /// </summary>
        public static string ChatRequestAssistance {
            get {
                return ResourceManager.GetString("ChatRequestAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar.
        /// </summary>
        public static string ChatRequestReject {
            get {
                return ResourceManager.GetString("ChatRequestReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe aqui....
        /// </summary>
        public static string ChatViewChatEntryPlaceHolder {
            get {
                return ResourceManager.GetString("ChatViewChatEntryPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antes de ponerte en contacto con un beneficiario, tienes que ponerte en línea..
        /// </summary>
        public static string ChatViewGoOnlineBeforeChat {
            get {
                return ResourceManager.GetString("ChatViewGoOnlineBeforeChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandonar conversación.
        /// </summary>
        public static string ChatViewLeaveConversation {
            get {
                return ResourceManager.GetString("ChatViewLeaveConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobando si hay voluntarios.
        /// </summary>
        public static string ChatViewLookingForVolunteers {
            get {
                return ResourceManager.GetString("ChatViewLookingForVolunteers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinicia filtros.
        /// </summary>
        public static string ChatViewResetFilter {
            get {
                return ResourceManager.GetString("ChatViewResetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string ChatViewSendMessage {
            get {
                return ResourceManager.GetString("ChatViewSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay voluntarios. Intentalo más tarde.
        /// </summary>
        public static string ChatViewThereAreNoVolunteers {
            get {
                return ResourceManager.GetString("ChatViewThereAreNoVolunteers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay voluntarios para el filtro que has puesto..
        /// </summary>
        public static string ChatViewThereAreNoVolunteersFiltered {
            get {
                return ResourceManager.GetString("ChatViewThereAreNoVolunteersFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil del voluntario.
        /// </summary>
        public static string ChatViewViewVolunteerProfile {
            get {
                return ResourceManager.GetString("ChatViewViewVolunteerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienes que esperar a que te llegue una solicitud.
        /// </summary>
        public static string ChatViewYouHaveToWaitRequest {
            get {
                return ResourceManager.GetString("ChatViewYouHaveToWaitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige voluntario.
        /// </summary>
        public static string ChoseVolunteerViewChoseVolunteer {
            get {
                return ResourceManager.GetString("ChoseVolunteerViewChoseVolunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añade un número.
        /// </summary>
        public static string CommonAddANumber {
            get {
                return ResourceManager.GetString("CommonAddANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion:.
        /// </summary>
        public static string CommonAddressTitle {
            get {
                return ResourceManager.GetString("CommonAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edad.
        /// </summary>
        public static string CommonAge {
            get {
                return ResourceManager.GetString("CommonAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edad:.
        /// </summary>
        public static string CommonAgeTitle {
            get {
                return ResourceManager.GetString("CommonAgeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar filtros.
        /// </summary>
        public static string CommonApplyFilters {
            get {
                return ResourceManager.GetString("CommonApplyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige tu petición.
        /// </summary>
        public static string CommonChooseRequestType {
            get {
                return ResourceManager.GetString("CommonChooseRequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige hospital.
        /// </summary>
        public static string CommonChoseHospital {
            get {
                return ResourceManager.GetString("CommonChoseHospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string CommonClose {
            get {
                return ResourceManager.GetString("CommonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        public static string CommonContinue {
            get {
                return ResourceManager.GetString("CommonContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string CommonDate {
            get {
                return ResourceManager.GetString("CommonDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar biografía.
        /// </summary>
        public static string CommonEdit {
            get {
                return ResourceManager.GetString("CommonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros.
        /// </summary>
        public static string CommonFilters {
            get {
                return ResourceManager.GetString("CommonFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Género.
        /// </summary>
        public static string CommonGender {
            get {
                return ResourceManager.GetString("CommonGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Género:.
        /// </summary>
        public static string CommonGenderTitle {
            get {
                return ResourceManager.GetString("CommonGenderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Es tu primera vez aqui?.
        /// </summary>
        public static string CommonIsYourFirstTime {
            get {
                return ResourceManager.GetString("CommonIsYourFirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado.
        /// </summary>
        public static string CommonList {
            get {
                return ResourceManager.GetString("CommonList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string CommonLogout {
            get {
                return ResourceManager.GetString("CommonLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string CommonMailTitle {
            get {
                return ResourceManager.GetString("CommonMailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa.
        /// </summary>
        public static string CommonMap {
            get {
                return ResourceManager.GetString("CommonMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre:.
        /// </summary>
        public static string CommonNameTitle {
            get {
                return ResourceManager.GetString("CommonNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva dirección.
        /// </summary>
        public static string CommonNewAddress {
            get {
                return ResourceManager.GetString("CommonNewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo chat.
        /// </summary>
        public static string CommonNewChat {
            get {
                return ResourceManager.GetString("CommonNewChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva petición.
        /// </summary>
        public static string CommonNewRequest {
            get {
                return ResourceManager.GetString("CommonNewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CommonNo {
            get {
                return ResourceManager.GetString("CommonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono:.
        /// </summary>
        public static string CommonPhoneTitle {
            get {
                return ResourceManager.GetString("CommonPhoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar lista.
        /// </summary>
        public static string CommonRefreshList {
            get {
                return ResourceManager.GetString("CommonRefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Términos y condiciones.
        /// </summary>
        public static string CommonTermsAndConditions {
            get {
                return ResourceManager.GetString("CommonTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptas los términos.
        /// </summary>
        public static string CommonTermsAndConditionsAccept {
            get {
                return ResourceManager.GetString("CommonTermsAndConditionsAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        public static string CommonTime {
            get {
                return ResourceManager.GetString("CommonTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string CommonYes {
            get {
                return ResourceManager.GetString("CommonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tus peticiones.
        /// </summary>
        public static string CommonYourRequests {
            get {
                return ResourceManager.GetString("CommonYourRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string CompletingRequestComments {
            get {
                return ResourceManager.GetString("CompletingRequestComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe un comentario adicional.
        /// </summary>
        public static string CompletingRequestCommentsPlaceHolder {
            get {
                return ResourceManager.GetString("CompletingRequestCommentsPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar petición.
        /// </summary>
        public static string CompletingRequestSendRequest {
            get {
                return ResourceManager.GetString("CompletingRequestSendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha y hora.
        /// </summary>
        public static string CompletingRequestTimeAndDate {
            get {
                return ResourceManager.GetString("CompletingRequestTimeAndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completa tu petición.
        /// </summary>
        public static string CompletingRequestTitle {
            get {
                return ResourceManager.GetString("CompletingRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AECC .
        /// </summary>
        public static string DashboardAppTitle {
            get {
                return ResourceManager.GetString("DashboardAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notif..
        /// </summary>
        public static string DashboardNotifications {
            get {
                return ResourceManager.GetString("DashboardNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica tu domicilio.
        /// </summary>
        public static string HomeAddressesListViewTitle {
            get {
                return ResourceManager.GetString("HomeAddressesListViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tus domicilios guardados.
        /// </summary>
        public static string HomeAddressesListViewYourAddresses {
            get {
                return ResourceManager.GetString("HomeAddressesListViewYourAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay coordinadores disponibles en esta provincia..
        /// </summary>
        public static string HomeRequestChooseTypeNoRequestsInProvince {
            get {
                return ResourceManager.GetString("HomeRequestChooseTypeNoRequestsInProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver todas las noticias.
        /// </summary>
        public static string HomeViewAllNews {
            get {
                return ResourceManager.GetString("HomeViewAllNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver todas mis peticiones.
        /// </summary>
        public static string HomeViewAllRequests {
            get {
                return ResourceManager.GetString("HomeViewAllRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chats online.
        /// </summary>
        public static string HomeViewChatsOnline {
            get {
                return ResourceManager.GetString("HomeViewChatsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat actual.
        /// </summary>
        public static string HomeViewCurrentChat {
            get {
                return ResourceManager.GetString("HomeViewCurrentChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Tienes dudas? Llámanos al 900 100 036.
        /// </summary>
        public static string HomeViewHeaderInfoBannerText {
            get {
                return ResourceManager.GetString("HomeViewHeaderInfoBannerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Últimas noticias.
        /// </summary>
        public static string HomeViewLastNews {
            get {
                return ResourceManager.GetString("HomeViewLastNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peticiones.
        /// </summary>
        public static string HomeViewRequests {
            get {
                return ResourceManager.GetString("HomeViewRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habla con un voluntario.
        /// </summary>
        public static string HomeViewTalkToVolunteer {
            get {
                return ResourceManager.GetString("HomeViewTalkToVolunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string HomeViewTitle {
            get {
                return ResourceManager.GetString("HomeViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica tu hospital.
        /// </summary>
        public static string HospitalAddressesListViewTitle {
            get {
                return ResourceManager.GetString("HospitalAddressesListViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tus hospitales guardados.
        /// </summary>
        public static string HospitalAddressesListViewYourAddresses {
            get {
                return ResourceManager.GetString("HospitalAddressesListViewYourAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quizás luego.
        /// </summary>
        public static string LocationPermissionsNegative {
            get {
                return ResourceManager.GetString("LocationPermissionsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string LocationPermissionsPositive {
            get {
                return ResourceManager.GetString("LocationPermissionsPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor activa en la configuracion de tu dispositivo el permiso de .
        /// </summary>
        public static string LocationPermissionsQuestion {
            get {
                return ResourceManager.GetString("LocationPermissionsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permiso de .
        /// </summary>
        public static string LocationPermissionsTitle {
            get {
                return ResourceManager.GetString("LocationPermissionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string LoginViewLogin {
            get {
                return ResourceManager.GetString("LoginViewLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario.
        /// </summary>
        public static string LoginViewUserPlaceHolder {
            get {
                return ResourceManager.GetString("LoginViewUserPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tienes ninguna dirección guardada. ¡Crea una nueva!.
        /// </summary>
        public static string NewHomeAddressListViewAddressesEmpty {
            get {
                return ResourceManager.GetString("NewHomeAddressListViewAddressesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hemos conseguido ninguna coincidencia. Por favor, revisa la dirección.
        /// </summary>
        public static string NewHomeAddressViewAddressesEmpty {
            get {
                return ResourceManager.GetString("NewHomeAddressViewAddressesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige una provincia.
        /// </summary>
        public static string NewHomeAddressViewChoseProvince {
            get {
                return ResourceManager.GetString("NewHomeAddressViewChoseProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar petición.
        /// </summary>
        public static string NewHomeAddressViewContinueRequest {
            get {
                return ResourceManager.GetString("NewHomeAddressViewContinueRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piso,Letra.
        /// </summary>
        public static string NewHomeAddressViewFloorPlaceHolder {
            get {
                return ResourceManager.GetString("NewHomeAddressViewFloorPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teclea la dirección y selecciónala de la lista.
        /// </summary>
        public static string NewHomeAddressViewHelp {
            get {
                return ResourceManager.GetString("NewHomeAddressViewHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplía la información.
        /// </summary>
        public static string NewHomeAddressViewMoreInfo {
            get {
                return ResourceManager.GetString("NewHomeAddressViewMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes nombrar esta dirección para guardarla..
        /// </summary>
        public static string NewHomeAddressViewMustNameTheAddress {
            get {
                return ResourceManager.GetString("NewHomeAddressViewMustNameTheAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponle un nombre a esta dirección.
        /// </summary>
        public static string NewHomeAddressViewNameTheAddressPlaceHolder {
            get {
                return ResourceManager.GetString("NewHomeAddressViewNameTheAddressPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han encontrado resultados con esta busqueda. Intentalo de nuevo..
        /// </summary>
        public static string NewHomeAddressViewNoHospitalsInList {
            get {
                return ResourceManager.GetString("NewHomeAddressViewNoHospitalsInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string NewHomeAddressViewNumberPlaceHolder {
            get {
                return ResourceManager.GetString("NewHomeAddressViewNumberPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal.
        /// </summary>
        public static string NewHomeAddressViewPortalPlaceHolder {
            get {
                return ResourceManager.GetString("NewHomeAddressViewPortalPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar esta dirección para futuras peticiones.
        /// </summary>
        public static string NewHomeAddressViewSaveAddress {
            get {
                return ResourceManager.GetString("NewHomeAddressViewSaveAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar dirección.
        /// </summary>
        public static string NewHomeAddressViewSearchAddress {
            get {
                return ResourceManager.GetString("NewHomeAddressViewSearchAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indica tu domicilio.
        /// </summary>
        public static string NewHomeAddressViewTitle {
            get {
                return ResourceManager.GetString("NewHomeAddressViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacion sobre servicios A.E.C.C..
        /// </summary>
        public static string NewHomeRequestChoseTypeAECCInfo {
            get {
                return ResourceManager.GetString("NewHomeRequestChoseTypeAECCInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acompañamiento en el domicilio.
        /// </summary>
        public static string NewHomeRequestChoseTypeHomeCompanion {
            get {
                return ResourceManager.GetString("NewHomeRequestChoseTypeHomeCompanion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apoyo en gestiones en el domicilio.
        /// </summary>
        public static string NewHomeRequestChoseTypeHomeManagement {
            get {
                return ResourceManager.GetString("NewHomeRequestChoseTypeHomeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactar con un profesional.
        /// </summary>
        public static string NewHomeRequestChoseTypeTalkToAnAECCProfesional {
            get {
                return ResourceManager.GetString("NewHomeRequestChoseTypeTalkToAnAECCProfesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estoy en casa.
        /// </summary>
        public static string NewHomeRequestSelectAddressImAtHome {
            get {
                return ResourceManager.GetString("NewHomeRequestSelectAddressImAtHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estoy en el hospital.
        /// </summary>
        public static string NewHomeRequestSelectAddressImAtHospital {
            get {
                return ResourceManager.GetString("NewHomeRequestSelectAddressImAtHospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hacer petición.
        /// </summary>
        public static string NewHomeRequestSelectAddressTitle {
            get {
                return ResourceManager.GetString("NewHomeRequestSelectAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás en el hospital o en tu domicilio? Elige desde dónde quieres hacer la petición..
        /// </summary>
        public static string NewHomeRequestSelectAddressWhereAreYouText {
            get {
                return ResourceManager.GetString("NewHomeRequestSelectAddressWhereAreYouText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Dónde estás?.
        /// </summary>
        public static string NewHomeRequestSelectAddressWhereAreYouTitle {
            get {
                return ResourceManager.GetString("NewHomeRequestSelectAddressWhereAreYouTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tienes ninguna dirección guardada. ¡Crea una nueva!.
        /// </summary>
        public static string NewHospitalAddressListViewAddressesEmpty {
            get {
                return ResourceManager.GetString("NewHospitalAddressListViewAddressesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles de la noticia.
        /// </summary>
        public static string NewsDetailViewTitle {
            get {
                return ResourceManager.GetString("NewsDetailViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexión perdida. Toca la pantalla para volver a intentarlo..
        /// </summary>
        public static string NoConnectionViewText {
            get {
                return ResourceManager.GetString("NoConnectionViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Vaya!.
        /// </summary>
        public static string NoConnectionViewTextTitle {
            get {
                return ResourceManager.GetString("NoConnectionViewTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Oh oh!.
        /// </summary>
        public static string PopupChatEventConnectionRejectedNotVolunteer {
            get {
                return ResourceManager.GetString("PopupChatEventConnectionRejectedNotVolunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petición rechazada.
        /// </summary>
        public static string PopupChatEventConnectionRejectedVolunteer {
            get {
                return ResourceManager.GetString("PopupChatEventConnectionRejectedVolunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PopupChatEventDeleteAggregation.
        /// </summary>
        public static string PopupChatEventDeleteAggregation {
            get {
                return ResourceManager.GetString("PopupChatEventDeleteAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconectado.
        /// </summary>
        public static string PopupChatEventDisconnected {
            get {
                return ResourceManager.GetString("PopupChatEventDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Lo sentimos!.
        /// </summary>
        public static string PopupChatEventSorry {
            get {
                return ResourceManager.GetString("PopupChatEventSorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si abandonas, la conversación se dará por finalizada y no podrás continuar conversando en el mismo chat..
        /// </summary>
        public static string PopupChatLeaseConversationText {
            get {
                return ResourceManager.GetString("PopupChatLeaseConversationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de que quieres abandonar la conversación?.
        /// </summary>
        public static string PopupChatLeaseConversationTextTitle {
            get {
                return ResourceManager.GetString("PopupChatLeaseConversationTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayúdanos a mejorar y evalúa tu experiencia en la conversacion con el voluntario..
        /// </summary>
        public static string PopupChatRatingText {
            get {
                return ResourceManager.GetString("PopupChatRatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Cómo ha sido tu experiencia?.
        /// </summary>
        public static string PopupChatRatingTextTitle {
            get {
                return ResourceManager.GetString("PopupChatRatingTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿En que habitación estás?.
        /// </summary>
        public static string PopupHospitalAskForRoomText {
            get {
                return ResourceManager.GetString("PopupHospitalAskForRoomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿En que sala estás?.
        /// </summary>
        public static string PopupHospitalAskForRoomTextTwo {
            get {
                return ResourceManager.GetString("PopupHospitalAskForRoomTextTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completa la informacion.
        /// </summary>
        public static string PopupHospitalAskForRoomTitle {
            get {
                return ResourceManager.GetString("PopupHospitalAskForRoomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vas a cerrar sesión y tendrás que volver a entrar la proxima vez..
        /// </summary>
        public static string PopupLogoutText {
            get {
                return ResourceManager.GetString("PopupLogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro?.
        /// </summary>
        public static string PopupLogoutTextTitle {
            get {
                return ResourceManager.GetString("PopupLogoutTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar localización.
        /// </summary>
        public static string PopupNoLocationProviderButtonYes {
            get {
                return ResourceManager.GetString("PopupNoLocationProviderButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es necesario activar la localización.
        /// </summary>
        public static string PopupNoLocationProviderText {
            get {
                return ResourceManager.GetString("PopupNoLocationProviderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para tener una localizacion más precisa es recomendable introducir un número, quieres continuar?.
        /// </summary>
        public static string PopupRequestAskForAddresNumberText {
            get {
                return ResourceManager.GetString("PopupRequestAskForAddresNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si deseas cambiar el tipo de petición, mantendremos los demás datos que has rellenado hasta ahora.
        /// </summary>
        public static string PopupRequestChangeRequestTypeText {
            get {
                return ResourceManager.GetString("PopupRequestChangeRequestTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de que quieres cambiar el tipo de petición?.
        /// </summary>
        public static string PopupRequestChangeRequestTypeTextTitle {
            get {
                return ResourceManager.GetString("PopupRequestChangeRequestTypeTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de que quieres enviar la petición?.
        /// </summary>
        public static string PopupRequestConfirmationTextTitle {
            get {
                return ResourceManager.GetString("PopupRequestConfirmationTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu petición ha sido enviada satisfactoriamente. Pronto te comunicaremos su estado..
        /// </summary>
        public static string PopupRequestSentText {
            get {
                return ResourceManager.GetString("PopupRequestSentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Gracias!.
        /// </summary>
        public static string PopupRequestSentTextTitle {
            get {
                return ResourceManager.GetString("PopupRequestSentTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acepto los términos y condiciones.
        /// </summary>
        public static string PopupTermsAndConditionsAccept {
            get {
                return ResourceManager.GetString("PopupTermsAndConditionsAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No encontramos una dirección valida, por favor revisa los datos.
        /// </summary>
        public static string PopupThereIsNoResultsText {
            get {
                return ResourceManager.GetString("PopupThereIsNoResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos!.
        /// </summary>
        public static string PopupThereIsNoResultsTextTitle {
            get {
                return ResourceManager.GetString("PopupThereIsNoResultsTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información personal.
        /// </summary>
        public static string PopupVolunteerProfileInfo {
            get {
                return ResourceManager.GetString("PopupVolunteerProfileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás en el hospital o en tu domicilio? Haz peticiones estés donde estés..
        /// </summary>
        public static string RequestsViewText {
            get {
                return ResourceManager.GetString("RequestsViewText", resourceCulture);
            }
        }
    }
}
